[package]
name = "toweth"
version = "0.1.0"
authors = ["James Prestwich <james@prestwi.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.2.2"
paste = "1.0.5"
proc-macro2 = "1.0.27"
quote = "1.0.9"
reqwest = "0.11.4"
serde = "1.0.126"
serde_json = "1.0.64"
serde_tuple = "0.5.0"
syn = "1.0.73"
tower = "0.4.8"
url = "2.2.2"
